// AUTO-GENERATED by tools/nukegen.py — DO NOT EDIT.
#include "reflect/Reflect.h"
#include "API/Model/Camera.h"
#include "API/Model/MeshRenderer.h"
#include "API/Model/Transform.h"

namespace nuke {
// Called once from World's constructor. Must be an EXTERNAL function called from a
// linked TU, otherwise the linker discards this .obj (and its registration) from
// the static lib (nothing else references it).
bool NukeReflectInit() {
	static bool _done = false;
	if (_done) return true;
	_done = true;
	{
		TypeInfo& t = TypeOf<Camera>();
		t.base = "Component";
		t.fields.push_back(MakeField("invertMouse", &Camera::invertMouse));
		t.fields.push_back(MakeField("r_width", &Camera::r_width));
		t.fields.push_back(MakeField("r_height", &Camera::r_height));
		t.fields.push_back(MakeField("fov", &Camera::fov));
		t.fields.push_back(MakeField("_near", &Camera::_near));
		t.fields.push_back(MakeField("_far", &Camera::_far));
		t.fields.push_back(MakeField("freeMode", &Camera::freeMode));
		t.fields.push_back(MakeField("depth", &Camera::depth));
		t.create = []() -> void* { return new Camera(); };
	}
	{
		TypeInfo& t = TypeOf<MeshRenderer>();
		t.base = "Component";
		t.fields.push_back(MakeField("meshGuid", &MeshRenderer::meshGuid, "mesh", "Mesh"));
		t.fields.push_back(MakeField("matGuid", &MeshRenderer::matGuid, "material", "Material"));
		t.create = []() -> void* { return new MeshRenderer(); };
	}
	{
		TypeInfo& t = TypeOf<Transform>();
		t.base = "Component";
		t.fields.push_back(MakeField("position", &Transform::position));
		t.fields.push_back(MakeField("rotation", &Transform::rotation));
		t.fields.push_back(MakeField("eulerHint", &Transform::eulerHint));
		t.fields.push_back(MakeField("scale", &Transform::scale));
	}
	return true;
}
}  // namespace nuke
