// AUTO-GENERATED by tools/nukegen.py — DO NOT EDIT.
#include "reflect/Reflect.h"
#include "API/Model/Camera.h"
#include "API/Model/Environment.h"
#include "API/Model/Light.h"
#include "API/Model/Material.h"
#include "API/Model/MeshRenderer.h"
#include "API/Model/Transform.h"

namespace nuke {
// Called once from World's constructor. Must be an EXTERNAL function called from a
// linked TU, otherwise the linker discards this .obj (and its registration) from
// the static lib (nothing else references it).
bool NukeReflectInit() {
	static bool _done = false;
	if (_done) return true;
	_done = true;
	{
		TypeInfo& t = TypeOf<Camera>();
		t.base = "Component";
		t.fields.push_back(MakeField("invertMouse", &Camera::invertMouse));
		t.fields.push_back(MakeField("r_width", &Camera::r_width));
		t.fields.push_back(MakeField("r_height", &Camera::r_height));
		t.fields.push_back(MakeField("fov", &Camera::fov));
		t.fields.push_back(MakeField("_near", &Camera::_near));
		t.fields.push_back(MakeField("_far", &Camera::_far));
		t.fields.push_back(MakeField("freeMode", &Camera::freeMode));
		t.fields.push_back(MakeField("depth", &Camera::depth));
		t.fields.push_back(MakeField("targetTexGuid", &Camera::targetTexGuid, "texture", "Target Texture"));
		t.create = []() -> void* { return new Camera(); };
	}
	{
		TypeInfo& t = TypeOf<Environment>();
		t.base = "Component";
		t.fields.push_back(MakeField("mode", &Environment::mode, "", "Mode", 0.0f, 0.0f, "None,Procedural"));
		t.fields.push_back(MakeField("skyTop", &Environment::skyTop, "", "Sky Top"));
		t.fields.push_back(MakeField("skyHorizon", &Environment::skyHorizon, "", "Sky Horizon"));
		t.fields.push_back(MakeField("skyGround", &Environment::skyGround, "", "Sky Ground"));
		t.fields.push_back(MakeField("skyIntensity", &Environment::skyIntensity, "", "Sky Intensity", 0.0f, 4.0f));
		t.fields.push_back(MakeField("ambient", &Environment::ambient, "", "Ambient"));
		t.fields.push_back(MakeField("ambientIntensity", &Environment::ambientIntensity, "", "Ambient Intensity", 0.0f, 2.0f));
		t.fields.push_back(MakeField("sunDisk", &Environment::sunDisk, "", "Sun Disk"));
		t.fields.push_back(MakeField("useTimeOfDay", &Environment::useTimeOfDay, "", "Time of Day"));
		t.fields.push_back(MakeField("hour", &Environment::hour, "", "Hour", 0.0f, 24.0f));
		t.fields.push_back(MakeField("daySpeed", &Environment::daySpeed, "", "Day Speed (h/s)", 0.0f, 4.0f));
		t.fields.push_back(MakeField("stars", &Environment::stars, "", "Stars"));
		t.fields.push_back(MakeField("starsTexGuid", &Environment::starsTexGuid, "texture", "Stars Texture"));
		t.fields.push_back(MakeField("moon", &Environment::moon, "", "Moon"));
		t.fields.push_back(MakeField("moonTexGuid", &Environment::moonTexGuid, "texture", "Moon Texture"));
		t.fields.push_back(MakeField("moonSize", &Environment::moonSize, "", "Moon Size (deg)", 0.5f, 30.0f));
		t.fields.push_back(MakeField("moonPhase", &Environment::moonPhase, "", "Moon Phase", 0.0f, 1.0f));
		t.create = []() -> void* { return new Environment(); };
	}
	{
		TypeInfo& t = TypeOf<Light>();
		t.base = "Component";
		t.fields.push_back(MakeField("type", &Light::type, "", "Type", 0.0f, 0.0f, "Directional,Point,Spot"));
		t.fields.push_back(MakeField("color", &Light::color, "", "Color"));
		t.fields.push_back(MakeField("intensity", &Light::intensity, "", "Intensity"));
		t.fields.push_back(MakeField("range", &Light::range, "", "Range"));
		t.fields.push_back(MakeField("spotAngle", &Light::spotAngle, "", "Spot Angle"));
		t.fields.push_back(MakeField("spotBlend", &Light::spotBlend, "", "Spot Blend"));
		t.fields.push_back(MakeField("castShadows", &Light::castShadows, "", "Cast Shadows"));
		t.create = []() -> void* { return new Light(); };
	}
	{
		TypeInfo& t = TypeOf<Material>();
		t.base = "Object";
		t.fields.push_back(MakeField("color", &Material::color, "", "Base Color"));
		t.fields.push_back(MakeField("diffuseGuid", &Material::diffuseGuid, "texture", "Base Color Map"));
		t.fields.push_back(MakeField("normalGuid", &Material::normalGuid, "texture", "Normal Map"));
		t.fields.push_back(MakeField("metalRoughGuid", &Material::metalRoughGuid, "texture", "Metallic-Roughness Map"));
		t.fields.push_back(MakeField("occlusionGuid", &Material::occlusionGuid, "texture", "Occlusion Map"));
		t.fields.push_back(MakeField("emissiveGuid", &Material::emissiveGuid, "texture", "Emissive Map"));
		t.fields.push_back(MakeField("metallic", &Material::metallic, "", "Metallic", 0.0f, 1.0f));
		t.fields.push_back(MakeField("roughness", &Material::roughness, "", "Roughness", 0.0f, 1.0f));
		t.fields.push_back(MakeField("emissive", &Material::emissive, "", "Emissive"));
		t.fields.push_back(MakeField("emissiveIntensity", &Material::emissiveIntensity, "", "Emissive Intensity"));
		t.fields.push_back(MakeField("castShadows", &Material::castShadows, "", "Cast Shadows"));
		t.fields.push_back(MakeField("shaderGuid", &Material::shaderGuid, "shader", "Shader"));
		t.create = []() -> void* { return new Material(); };
	}
	{
		TypeInfo& t = TypeOf<MeshRenderer>();
		t.base = "Component";
		t.fields.push_back(MakeField("meshGuid", &MeshRenderer::meshGuid, "mesh", "Mesh"));
		t.fields.push_back(MakeField("matGuid", &MeshRenderer::matGuid, "material", "Material"));
		t.create = []() -> void* { return new MeshRenderer(); };
	}
	{
		TypeInfo& t = TypeOf<Transform>();
		t.base = "Component";
		t.fields.push_back(MakeField("position", &Transform::position));
		t.fields.push_back(MakeField("rotation", &Transform::rotation));
		t.fields.push_back(MakeField("eulerHint", &Transform::eulerHint));
		t.fields.push_back(MakeField("scale", &Transform::scale));
	}
	return true;
}
}  // namespace nuke
