#pragma once
#ifndef NUKEE_ICONS_FILE_TYPES_H
#define NUKEE_ICONS_FILE_TYPES_H

// The glyph vocabulary a file type can name when it registers itself
// (AssetCreator::icon / RegisterFileIcon): source files use the Seti-UI set — the same
// glyphs VS Code's file explorer draws — and asset kinds use the Font Awesome / Octicons /
// Codicons subsets. All of it is subset out of the Nerd Fonts symbols font (MIT) and
// RE-MAPPED into plane 15: the source codepoints overlap Lucide's range, and two merged
// fonts cannot share a slot. Needs IMGUI_USE_WCHAR32; the editor merges
// fonts/nukefileicons.ttf over the range below.
//
// GENERATED by NukeUtils/nukeicons.py — do not edit by hand.

#define FONT_ICON_FILE_NAME_FT "nukefileicons.ttf"

#define ICON_MIN_FT 0xf0100
#define ICON_MAX_FT 0xf0133

#define ICON_FT_CPP            "\xf3\xb0\x84\x80"   // U+F0100
#define ICON_FT_C              "\xf3\xb0\x84\x81"   // U+F0101
#define ICON_FT_CSHARP         "\xf3\xb0\x84\x82"   // U+F0102
#define ICON_FT_LUA            "\xf3\xb0\x84\x83"   // U+F0103
#define ICON_FT_PYTHON         "\xf3\xb0\x84\x84"   // U+F0104
#define ICON_FT_JSON           "\xf3\xb0\x84\x85"   // U+F0105
#define ICON_FT_XML            "\xf3\xb0\x84\x86"   // U+F0106
#define ICON_FT_MARKDOWN       "\xf3\xb0\x84\x87"   // U+F0107
#define ICON_FT_TEXT           "\xf3\xb0\x84\x88"   // U+F0108
#define ICON_FT_CONFIG         "\xf3\xb0\x84\x89"   // U+F0109
#define ICON_FT_SHELL          "\xf3\xb0\x84\x8a"   // U+F010A
#define ICON_FT_POWERSHELL     "\xf3\xb0\x84\x8b"   // U+F010B
#define ICON_FT_MAKEFILE       "\xf3\xb0\x84\x8c"   // U+F010C
#define ICON_FT_FONT           "\xf3\xb0\x84\x8d"   // U+F010D
#define ICON_FT_IMAGE          "\xf3\xb0\x84\x8e"   // U+F010E
#define ICON_FT_AUDIO          "\xf3\xb0\x84\x8f"   // U+F010F
#define ICON_FT_VIDEO          "\xf3\xb0\x84\x90"   // U+F0110
#define ICON_FT_ZIP            "\xf3\xb0\x84\x91"   // U+F0111
#define ICON_FT_DB             "\xf3\xb0\x84\x92"   // U+F0112
#define ICON_FT_LOCK           "\xf3\xb0\x84\x93"   // U+F0113
#define ICON_FT_FOLDER         "\xf3\xb0\x84\x94"   // U+F0114
#define ICON_FT_HTML           "\xf3\xb0\x84\x95"   // U+F0115
#define ICON_FT_CSS            "\xf3\xb0\x84\x96"   // U+F0116
#define ICON_FT_JAVASCRIPT     "\xf3\xb0\x84\x97"   // U+F0117
#define ICON_FT_ASM            "\xf3\xb0\x84\x98"   // U+F0118
#define ICON_FT_PROJECT        "\xf3\xb0\x84\x99"   // U+F0119
#define ICON_FT_LICENSE        "\xf3\xb0\x84\x9a"   // U+F011A
#define ICON_FT_INFO           "\xf3\xb0\x84\x9b"   // U+F011B
#define ICON_FT_GIT            "\xf3\xb0\x84\x9c"   // U+F011C
#define ICON_FT_DEFAULT        "\xf3\xb0\x84\x9d"   // U+F011D
#define ICON_FT_MESH           "\xf3\xb0\x84\x9e"   // U+F011E
#define ICON_FT_MESH_INSTANCED "\xf3\xb0\x84\x9f"   // U+F011F
#define ICON_FT_MATERIAL       "\xf3\xb0\x84\xa0"   // U+F0120
#define ICON_FT_PREFAB         "\xf3\xb0\x84\xa1"   // U+F0121
#define ICON_FT_ANIM           "\xf3\xb0\x84\xa2"   // U+F0122
#define ICON_FT_SKELETON       "\xf3\xb0\x84\xa3"   // U+F0123
#define ICON_FT_BONEMAP        "\xf3\xb0\x84\xa4"   // U+F0124
#define ICON_FT_STATEMACHINE   "\xf3\xb0\x84\xa5"   // U+F0125
#define ICON_FT_BLENDSPACE     "\xf3\xb0\x84\xa6"   // U+F0126
#define ICON_FT_SEQUENCE       "\xf3\xb0\x84\xa7"   // U+F0127
#define ICON_FT_RAGDOLL        "\xf3\xb0\x84\xa8"   // U+F0128
#define ICON_FT_WORLD          "\xf3\xb0\x84\xa9"   // U+F0129
#define ICON_FT_SHADER         "\xf3\xb0\x84\xaa"   // U+F012A
#define ICON_FT_VFX            "\xf3\xb0\x84\xab"   // U+F012B
#define ICON_FT_WATER          "\xf3\xb0\x84\xac"   // U+F012C
#define ICON_FT_FOLIAGE        "\xf3\xb0\x84\xad"   // U+F012D
#define ICON_FT_TILEMAP        "\xf3\xb0\x84\xae"   // U+F012E
#define ICON_FT_INPUT          "\xf3\xb0\x84\xaf"   // U+F012F
#define ICON_FT_PACKAGE        "\xf3\xb0\x84\xb0"   // U+F0130
#define ICON_FT_MOD            "\xf3\xb0\x84\xb1"   // U+F0131
#define ICON_FT_SAVE           "\xf3\xb0\x84\xb2"   // U+F0132
#define ICON_FT_SETTINGS       "\xf3\xb0\x84\xb3"   // U+F0133

#endif // !NUKEE_ICONS_FILE_TYPES_H
