# Re-applies the CRT / iterator-debug patches to the generated bgfx/bx/bimg
# Visual Studio project files so they link against the SAME runtime as the rest
# of NukeEngine (dynamic debug CRT, /MDd, _ITERATOR_DEBUG_LEVEL=2).
#
# WHY THIS EXISTS:
#   deps/bgfx/.build/projects/vs2019/*.vcxproj are generated by genie and are
#   git-ignored, so these edits are NOT tracked by git. They live only on disk.
#   If you ever run `git clean -xfd` inside deps/bgfx or regenerate the projects
#   with genie, the patches vanish and the editor fails to link with errors like
#   `unresolved external symbol __imp__CrtDbgReport` or
#   `mismatch detected for '_ITERATOR_DEBUG_LEVEL'`.
#   Run this script to restore them. It is idempotent (safe to run repeatedly).
#
# Usage:  powershell -ExecutionPolicy Bypass -File tools\fix-bgfx-crt.ps1

$ErrorActionPreference = 'Stop'
$base = Join-Path $PSScriptRoot '..\deps\bgfx\.build\projects\vs2019'
$files = 'bgfx.vcxproj','bx.vcxproj','bimg.vcxproj' | ForEach-Object { Join-Path $base $_ }

foreach ($f in $files) {
    if (-not (Test-Path $f)) { Write-Warning "missing (run genie first?): $f"; continue }
    $c = Get-Content -Raw -Encoding UTF8 $f
    $orig = $c

    # 1) static debug CRT -> dynamic debug CRT, static release -> dynamic release
    $c = $c.Replace('MultiThreadedDebug</RuntimeLibrary>', 'MultiThreadedDebugDLL</RuntimeLibrary>')
    $c = $c -replace '(?<!DLL)MultiThreaded</RuntimeLibrary>', 'MultiThreadedDLL</RuntimeLibrary>'

    # 2) DEBUG configs only: enable full iterator debugging to match the app/vcpkg
    $c = $c.Replace(
        '_DEBUG;WIN32;_WIN32;_HAS_EXCEPTIONS=0;_HAS_ITERATOR_DEBUGGING=0;_ITERATOR_DEBUG_LEVEL=0',
        '_DEBUG;WIN32;_WIN32;_HAS_EXCEPTIONS=0;_HAS_ITERATOR_DEBUGGING=1;_ITERATOR_DEBUG_LEVEL=2')
    # 3) iterator debug level 2 requires secure SCL == 1
    $c = $c.Replace(
        '_ITERATOR_DEBUG_LEVEL=2;_SCL_SECURE=0;_SECURE_SCL=0',
        '_ITERATOR_DEBUG_LEVEL=2;_SCL_SECURE=1;_SECURE_SCL=1')

    if ($c -ne $orig) {
        Set-Content -Path $f -Value $c -Encoding UTF8 -NoNewline
        Write-Output ("patched : {0}" -f (Split-Path $f -Leaf))
    } else {
        Write-Output ("ok      : {0} (already patched)" -f (Split-Path $f -Leaf))
    }
}
